# -*- coding: utf-8 -*-
"""yahoofinance-library.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15rVryTwoJiMaw45x5iFHU2doo9ylNG9i
"""

!pip install yfinance
import pandas as pd
import yfinance as yf
emiten = input()
ticker = yf.Ticker(emiten)

ticker.balance_sheet

ticker.financials

ticker.cashflow

financial = [ticker.financials, ticker.balancesheet, ticker.cashflow]
result = pd.concat(financial)
df = pd.DataFrame.from_dict(result, orient='columns')
df.to_excel(emiten + '.xlsx')